# Cas 1
FROM maven:3.9-eclipse-temurin-21 AS builder

WORKDIR /build

COPY pom.xml .
RUN mvn dependency:go-offline -B

COPY src ./src

RUN mvn clean package

# cas 2
FROM eclipse-temurin:21-jre-alpine

WORKDIR /app

COPY --from=builder /build/target/tp_archi_step_1-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]

