apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2
  namespace: labotrack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service2
  template:
    metadata:
      labels:
        app: service2
    spec:
      containers:
        - name: service2
          image: labotrack/service2:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 9001
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9001
            initialDelaySeconds: 20
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: service2
  namespace: labotrack
spec:
  selector:
    app: service2
  ports:
    - port: 9001
      targetPort: 9001
---

apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: service2.labotrack.svc.cluster.local
  namespace: labotrack
spec:
  routes:
    - name: POST /api/analyze
      condition:
        method: POST
        pathRegex: /api/analyze
      timeout: 15s
      isRetryable: false
